                            Programming Assignment no. 08

1. Write a Python Program to Add Two Matrices?

In [27]:
A = [[8, 9, 11],
     [7, 11, 14],
     [10, 22, 28]]
     

B = [[3, 6, 16],
     [5, 13, 17],
     [19, 21, 26]]
     
     
result = [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]
          
          
          
#iterate through rows

for x in range(len(A)):
    # iterate through columns
    for y in range(len(A[0])):
        result[x][y] = A[x][y] + B[x][y]
        
print("After adding two matrices: \n")

for q in result:
    print(q)

After adding two matrices: 

[11, 15, 27]
[12, 24, 31]
[29, 43, 54]


In [26]:
# Using numpy 
import numpy as np

matrix1 = np.array([[8, 9, 11],
             [7, 11, 14],
             [10, 22, 28]])
     

matrix2 = np.array([[3, 6, 16],
     [5, 13, 17],
     [19, 21, 26]])

matrixsum = np.add(matrix1,matrix2)
print("The sum of two matrix is \n\n {} and \n\n{}  is \n\n{} ".format(matrix1,matrix2,matrixsum))

The sum of two matrix is 

 [[ 8  9 11]
 [ 7 11 14]
 [10 22 28]] and 

[[ 3  6 16]
 [ 5 13 17]
 [19 21 26]]  is 

[[11 15 27]
 [12 24 31]
 [29 43 54]] 


2. Write a Python Program to Multiply Two Matrices?

In [37]:
A = [[3, 5, 7],
     [9, 13, 19],
     [16, 23, 27]]

B = [[1, 4, 6, 9],
     [2, 8, 10, 14],
     [3, 7, 15, 17]]

result = [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]

# iterate through rows of matrix A
for i in range(len(A)):
    # iterate through columns of matrix B
    for j in range(len(B[0])):
        # iterates through row of natrix B
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
            
print("After Multiplication matrix is: \n")
for r in result:
    print(r)

After Multiplication matrix is: 

[34, 101, 173, 216]
[92, 273, 469, 586]
[143, 437, 731, 925]


In [39]:
# using numpy

import numpy as np

A = np.array([[3, 5, 7],
     [9, 13, 19],
     [16, 23, 27]])

B = np.array([[1, 4, 6, 9],
     [2, 8, 10, 14],
     [3, 7, 15, 17]])

matrixmult = np.dot(A,B)

print("The product of two matrix \n\n{}  and  \n\n{}   is  \n\n{} ".format(A, B, matrixmult))

The product of two matrix 

[[ 3  5  7]
 [ 9 13 19]
 [16 23 27]]  and  

[[ 1  4  6  9]
 [ 2  8 10 14]
 [ 3  7 15 17]]   is  

[[ 34 101 173 216]
 [ 92 273 469 586]
 [143 437 731 925]] 


3. Write a Python Program to Transpose a Matrix?

In [41]:
matrix = [[1, 3, 5], 
          [4, 6, 8]]
print("Original Matrix is :")

for i in matrix:
    print(i)
print('And')
m = len(matrix)
n = len(matrix[0])

result = [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]
print("Transported Matrix is :")
for i in result:
    print(i)

Original Matrix is :
[1, 3, 5]
[4, 6, 8]
And
Transported Matrix is :
[1, 4]
[3, 6]
[5, 8]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [42]:
Arr = input("Enter String")

words = Arr.split()
words.sort()
for word in words:
    print(word)

Enter String Data Science is Leading Tech Career


Career
Data
Leading
Science
Tech
is


In [43]:
word = input("Enter a Word")

# splitting word into form of list

split = list(word)
print(split)

# Sorting list by an Alphabetical Order

split.sort()

# Joining list letters to make word

string = " ".join(split)
print(string)


Enter a Word bharat


['b', 'h', 'a', 'r', 'a', 't']
a a b h r t


5. Write a Python Program to Remove Punctuation From a String?

In [44]:
import re

def remove_punctuation(string):
    
    """Removes punctuations from a string.
    
    Args:
    String: The string to remove punctuations from.
    
    Returns: 
    A string with punctuation removed.
    
    """
    
    # Create a regular expression to match all punctuation characters.
    punctuation = re.compile(r"[^\w\s]")
    
    # Replace all punctuation characters with spaces.
    return punctuation.sub("", string)


In [45]:
string = "This is a string ! with punctuation."
print(remove_punctuation(string))

This is a string  with punctuation
